### ISSUE TITLE
Where is firebase file

### ISSUE THREAD

**Issue by YousefAlsbaihi** [curlos/netflix-clone#1]
Can you share the Firebase file content ?

**Comment by curlos** [comment]
> Can you share the Firebase file content ?

I assume you're here from Sonny's channel? In his video he uses the old version of Firebase so our files are really different. If you're looking for a video showing Firebase V9, this person did a good clone of Twitter using a similar file structure as myself here. 

Video: https://www.youtube.com/watch?v=5Wak0iyGCrc&t=19422s
Link to their repo: https://github.com/lukef7fywmrp/twitter-clone
Link to their firebase.js file: https://github.com/lukef7fywmrp/twitter-clone/blob/main/firebase.js
